#./dbt_project.yml
name: 'dlt_ddb_dbt'
version: '1.0.0'

# Profile to use
profile: 'dlt_ddb_dbt'

# File path configurations
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  dlt_ddb_dbt:
    publish:
      +materialized: view
      +schema: publish
      +tags: publish

    work:
      +materialized: table
      +schema: work
      +tags: work

    stg:
      +materialized: view
      +schema: stg
      +tags: stg
