dlt_ddb_dbt:
  outputs:
    dev:
      type: duckdb
      schema: main
      path: md:dev
      threads: 1
      attach:
        - path: md:source
          alias: source

    prod:
      type: duckdb
      schema: main
      path: md:prod
      threads: 1
      attach:
        - path: md:source
          alias: source

  target: dev
